version: '2'
services:
    labtel-app:
        image: labtel
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://labtel-mysql:3306/labtel?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    labtel-mysql:
        extends:
            file: mysql.yml
            service: labtel-mysql
